# Generated by Django 5.1.7 on 2025-03-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_movie_review_delete_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_on']},
        ),
    ]
